mysite/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('welcome.urls')),

]

welcome/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView

from welcome.views import search_classes
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view(), name='logout'),
    path('profile', views.EditView.as_view(), name='profile'),
    path('profile/edit_classes', views.edit_classes, name='classes'),
    path('profile/edit_classes/delete', views.delete_class, name='delete'),
    path('profile/edit_classes/add', views.add_classes, name='add'),
    path('profile/edit_classes/<str:subject>/', views.subject_view, name='class_view'),
    path('viewuser/<int:user_id>/', views.view_other_user, name='viewuser'),
    path('classes/search', views.search_classes, name ='search'),
    path('update', views.update, name='update'),
    path('updatetimes', views.updateTimes, name='updatetimes'),
    path('newmeeting/<int:reciever_id>', views.new_meeting, name='newmeeting'),
    path('newmeeting/<int:reciever_id>/submit', views.confirm_meeting, name='confmeeting'),
    path('edit_meeting/<int:meeting_id>', views.edit_meeting, name='edit_meeting'),
    path('edit_meeting/<int:meeting_id>/update', views.update_meeting, name='update_meeting'),
    path('edit_meeting/<int:meeting_id>/delete', views.delete_meeting, name='delete_meeting'),
    path('send_friend_request/<int:userID>/', views.send_friend_request, name='send friend request'),
    path('accept_friend_request/<int:requestID>/', views.accept_friend_request, name='accept friend request'),
    path('decline_friend_request/<int:requestID>/', views.decline_friend_request, name='decline friend request'),
    path('friends', views.friends, name='friends'),
    path('chat/<str:room_name>', views.room, name='room'),
    path('myprofile/updatetimes', views.updateTimes, name='updatetimes'),
    path('myprofile', views.view_myprofile, name='myprofile'),
    path('myprofile/savebio', views.save_bio, name='savebio'),
    path('remove_friend/<int:userID>/', views.remove_friend, name='remove_friend'),
]

welcome/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class UserClasses(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=10)
    catalog_number = models.IntegerField()
    component = models.CharField(max_length=10)
    section = models.IntegerField()
    professor = models.CharField(max_length=200)
    available = models.BooleanField(default=False)
    description = models.CharField(max_length=200)

    def __str__(self):
        if self.professor == "-":
            return self.subject + " " + str(self.catalog_number) + " " + self.component + " Section " + str(self.section)
        else:
            return self.subject + " " + str(self.catalog_number) + " " + self.component + " Section " + str(self.section) + " w/ " + self.professor

    def as_array(self):
        return [self.subject, self.catalog_number, self.component]


class FriendList(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user")
    friends = models.ManyToManyField(User, blank=True)


class Friend_Request(models.Model):
    from_user = models.ForeignKey(User, related_name='from_user', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name='to_user', on_delete=models.CASCADE)


class Class(models.Model):
    Name = models.CharField(max_length=150)
    Proffessor = models.CharField(max_length=150)
    students = models.ManyToManyField(User ,related_name = 'classes')


class UserToUserChat(models.Model):
    user1 = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name = 'user1')
    user2 = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name = 'user2')
    roomName = models.CharField(max_length=128, unique=True)


class Day(models.Model):
    day = models.CharField(max_length=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Time(models.Model):
    available = models.BooleanField(default =False)
    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    time = models.CharField(max_length = 10)

class Message(models.Model):
    room = models.ForeignKey(UserToUserChat, related_name='chat', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',)

class Bio(models.Model):
    content = models.TextField()
    student = models.OneToOneField(User, on_delete=models.CASCADE)


class meeting(models.Model):
    date = models.DateField()
    time = models.TimeField()
    title = models.CharField(max_length=150)
    participants = models.ManyToManyField(User, related_name='meetings')

welcome/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from datetime import datetime

class EditProfileForm(UserChangeForm):
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = None

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')

class MeetingForm(forms.Form):
    title = forms.CharField(max_length=100, required=True)
    date = forms.DateField()
    time = forms.TimeField()


     

welcome/views.py
from django.views import generic
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseBadRequest
from django.urls import reverse
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from django.shortcuts import redirect
from .forms import EditProfileForm
from .models import UserClasses, Class, UserToUserChat, Time, Day, meeting, Bio, Message
import json
import ast
import requests
from itertools import groupby
from django.core.exceptions import ValidationError
from .models import Friend_Request
from .models import Class
from .models import FriendList
from django.db.models import Q
from datetime import datetime

import string
import random


def index(request):
    if request.user.is_authenticated:
        meetings = meeting.objects.filter(participants=request.user, date__gte = datetime.today()).order_by('date')
        meetings_old = meeting.objects.filter(date__lt = datetime.today())

        for old_meeting in meetings_old:
            old_meeting.delete()

        sent_requests = []
        for thisRequest in request.user.from_user.all():
            sent_requests.append(thisRequest.to_user)

        received_requests = []
        user_to_id = {}
        for thisRequest in request.user.to_user.all():
            received_requests.append(thisRequest.from_user)
            user_to_id[thisRequest.from_user.id] = thisRequest.id

        if not request.user.day_set.all():
            days = ['M','T','W','Th','F','Sa','Su']
            for day in days:
                thisday = Day.objects.create(user= request.user, day = day)
                for j in range(10, 23):
                    Time.objects.create(day = thisday, time = str(j)+":00")
        active =[]
        if request.user.classes.all():
            active.append( request.user.classes.all()[0])

        
        return render(request, 'welcome/index.html', {'meetings': meetings, 'sent_requests' : sent_requests, 'received_requests': received_requests, 'active':active, 'user_to_id': user_to_id })

    return render(request, 'welcome/index.html')


class EditView(generic.UpdateView):
    form_class = EditProfileForm
    template_name = 'welcome/profile.html'
    success_url = reverse_lazy('index')

    def get_object(self):
        return self.request.user


def edit_classes(request):
    template_name = 'welcome/edit_classes.html'

    # Basic idea for displaying JSON into a view. Parse the JSON in here (or in another file/function?) 
    # and pass it as a list of lists (or other) in the render.

    dept_list = requests.get('http://luthers-list.herokuapp.com/api/deptlist/?format=json').json()
    return render(request, template_name, {'dept_list': dept_list})


def delete_class(request):
    template_name = 'welcome/edit_classes.html'
    try:
        selected_classes = request.POST.getlist('class_to_delete')
        class_ids = []
        for c in selected_classes:
            class_ids.append(request.user.userclasses_set.get(pk=c))
    except(KeyError):
        return HttpResponseRedirect(reverse('classes'))
    else:
        for id in class_ids:
            try:
                thisclass = Class.objects.get(Name=id.subject + str(id.catalog_number))
                thisclass.students.remove(request.user)
            except(KeyError):
                pass
            id.delete()

        return HttpResponseRedirect(reverse('classes'))


def add_classes(request):
    try:
        selected_classes = request.POST.getlist('class_to_add')
    except(KeyError):
        return HttpResponseRedirect(reverse('classes'))
    
    else:
        add = True
        for class_to_add in selected_classes:
            c = class_to_add.split("/")
            UserClasses.objects.create(user=request.user,subject=c[0], catalog_number=c[1], component=c[2], section=c[3], professor=c[4], description=c[5])
        return HttpResponseRedirect(reverse('classes'))


def subject_view(request, subject):
    classes = requests.get('http://luthers-list.herokuapp.com/api/dept/' + subject + '/?format=json').json()
    
    current_classes = UserClasses.objects.filter(user=request.user)

    result = {
            key : list(group) for key, group in groupby(classes,key=lambda x:x['subject'] + " " + x['catalog_number'] + " " + x['description'])
           } 

    return render(request, 'welcome/subject.html', {'classes': result, 'current_classes': current_classes, "sub": subject})


def search_classes(request):
    searchPhrase = request.POST['searchbox']
    foundClasses = []
    response = requests.get('http://luthers-list.herokuapp.com/api/dept/CS/?format=json').json()
    for thisClass in response:
        if searchPhrase in thisClass["description"]:
            foundClasses.append(thisClass)
    return render(request, 'welcome/home.html', {'response': foundClasses})


def view_other_user(request, user_id):
    if user_id == request.user.id:
        return view_myprofile(request)
    
    student = get_object_or_404(User, pk=user_id)

    requests = []
    for thisRequest in request.user.from_user.all():
        requests.append(thisRequest.to_user)

    return render(request, 'welcome/other_profile.html', {'student' : student, 'sent_requests': requests} )


def update(request):
    try:
        selected_classes = request.POST.getlist('class_to_update')
        class_ids = []
        for c in selected_classes:
            class_ids.append(request.user.userclasses_set.get(pk=c))
    except(KeyError):
        return HttpResponseRedirect(reverse('index'))

    else:
        toAdd = []
        for c in request.user.userclasses_set.all():

            if c in class_ids:
                c.available = True
                c.save()
                try:
                    thisclass = Class.objects.get(Name=c.subject + str(c.catalog_number))
                except:
                    thisclass = Class.objects.create(Name=c.subject + str(c.catalog_number))

                toAdd.append(thisclass)

            else:
                c.available = False
                c.save()
                try:
                    thisclass = Class.objects.get(Name=c.subject + str(+c.catalog_number))
                    thisclass.students.remove(request.user)
                except:
                    pass
        for each in toAdd:
            each.students.add(request.user)

        return HttpResponseRedirect(reverse('index'))


def send_friend_request(request, userID):
    from_user = request.user
    to_user = User.objects.get(id=userID)
    Friend_Request.objects.get_or_create(from_user=from_user, to_user=to_user)
    return HttpResponseRedirect(reverse('index'))


def accept_friend_request(request, requestID):
    friend_request = Friend_Request.objects.get(id=requestID)
    current_list = FriendList.objects.select_related().filter(user=request.user.id)
    if not current_list.exists():
        friend_list = FriendList()
        friend_list.user = friend_request.to_user
        friend_list.save()
        friend_list.friends.add(friend_request.from_user)
        friend_list.save()
        add_friend_back(friend_request.from_user, friend_request.to_user)
        # trying to add user back on both lists
        # friend_list.from_user
        if request.method == "POST":
            friend_request.delete()
        return HttpResponseRedirect(reverse('friends'))
    for i in current_list:
        i.friends.add(friend_request.from_user)
        add_friend_back(friend_request.from_user, friend_request.to_user)
        if request.method == "POST":
            friend_request.delete()
            return HttpResponseRedirect(reverse('friends'))


def add_friend_back(to_user, from_user):

    room_name = ''.join(random.choices(string.ascii_lowercase + string.digits, k=9))
    private_chat = UserToUserChat(user1=to_user, user2=from_user, roomName=room_name)
    private_chat.save()

    current_list = FriendList.objects.select_related().filter(user=to_user)
    if not current_list.exists():
        friend_list = FriendList()
        friend_list.user = to_user
        friend_list.save()
        friend_list.friends.add(from_user)
        friend_list.save()
        return HttpResponseRedirect(reverse('friends'))
    for i in current_list:
        i.friends.add(from_user)
        return HttpResponseRedirect(reverse('friends'))


def decline_friend_request(request, requestID):
    friend_request = Friend_Request.objects.get(id=requestID)
    if request.method == "POST":
        friend_request.delete()
        return HttpResponseRedirect(reverse('friends'))
    return HttpResponseRedirect(reverse('friends'))


def remove_friend(request, userID):
    if request.method == "POST":
        from_user = request.user
        to_user = User.objects.get(id=userID)
        to_user_friendlist = FriendList.objects.get(user=to_user)
        from_user_friendlist = FriendList.objects.get(user=from_user)

        if to_user_friendlist:
            to_user_friendlist.friends.remove(from_user)
        if from_user_friendlist:
            from_user_friendlist.friends.remove(to_user)

        room = UserToUserChat.objects.filter(user1=from_user, user2=to_user) | UserToUserChat.objects.filter(user1=to_user, user2=from_user)
        room.delete()
        
        meetings_with_friend = meeting.objects.filter(participants=from_user) & meeting.objects.filter(participants=to_user)
        for to_delete in meetings_with_friend:
            to_delete.delete()

    return HttpResponseRedirect(reverse('friends'))


def study_partners(request):
    if request.user.UserClasses.available == True:
        same_classes_available = UserClasses.objects.filter(search_classes=request.user.UserClasses.search_class, available=True).exclude(id=request.user.id)

welcome/templates/welcome/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <strong>Select Your Current Courses</strong>
    <form action = "{% url 'search' %}" method="post" class="form">
        {% csrf_token %}
        <input type="text" id="searchbox" name="searchbox">
        <input type="submit" value="Search">
    </form>
    {% for i in response %}
        <div>{{i.subject}} {{i.catalog_number}} {{i.description}}</div>
    {% endfor %}
</body>
</html>

welcome/templates/welcome/myprofile.html
{% load socialaccount %}
{% load bootstrap5 %}
{% load static %}
{% load custom_tags %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% include 'welcome/base.html' %}

{% block content %}
<body style=" background-color:#159ec8c2;">
    
    <div class="d-flex justify-content-center" >
        <div class="bg-light d-flex justify-content-center" style="height: 750px; width: 850;">
            <div class="bg-light" style="height: 450px; width: 561;">
                <div class="border-bottom border-dark"><h1>{{ student.first_name }} {{student.last_name }}</h1></div>
                <br>
                <form action="{% url 'savebio' %}" method="post">
                    {% csrf_token %}
                    <h4>My Bio:</h4>
                    <div class="text-center" >
                        <textarea class="form-control" id="txtarea" name="bio" rows="4" style="resize: none;">{{ contents }}</textarea>
                        
                    </div>
                    <button class="btn btn-primary" type="submit">Save Bio</button>
                </form>
                <br>
                <form action="{% url 'updatetimes' %}" method="post">
                    {% csrf_token %}
                    <div style=" background-color:#f7f3f3;">
                        <h4 class="text-center">My Availablility:</h4>
                        <div class="container text-center">
                            <div class="row gx-0 gy-0">
                                <div class="col-md-2" style="height: 345px; width: 75">
                                    <div class="text-end" style="height: 20px; width: 0"></div>
                                    <div class="text-end" style="height: 24px; width: 0">10:00AM</div>
                                    <div class="text-end" style="height: 24px; width: 0">11:00AM</div>
                                    <div class="text-end" style="height: 24px; width: 0">12:00PM</div>
                                    <div class="pull-end" style="height: 24px; width: 0">1:00PM</div>
                                    <div class="pull-right" style="height: 24px; width: 0">2:00PM</div>
                                    <div class="text-center" style="height: 24px; width: 0">3:00PM</div>
                                    <div class="text-end" style="height: 24px; width: 0">4:00PM</div>
                                    <div class="text-end" style="height: 24px; width: 0">5:00PM</div>
                                    <div class="text-end" style="height: 24px; width: 0">6:00PM</div>
                                    <div class="text-end" style="height: 24px; width: 0">7:00PM</div>
                                    <div class="text-end" style="height: 24px; width: 0">8:00PM</div>
                                    <div class="text-end" style="height: 24px; width: 0">9:00PM</div>
                                    <div class="text-end" style="height: 24px; width: 0">10:00PM</div>
                                </div>
                                <div class = "col-lg">
                                    <div class ="row gx-0 gy-0">
                                        <h5 class="col-sm">Mon.</h5>
                                        <h5 class="col-sm">Tues.</h5>
                                        <h5 class="col-sm">Wed.</h5>
                                        <h5 class="col-sm">Thur.</h5>
                                        <h5 class="col-sm">Fri.</h5>
                                        <h5 class="col-sm">Sat.</h5>
                                        <h5 class="col-sm">Sun.</h5>
                                    </div>
                                    <div class="row gx-0 gy-0">
                                        {% for day in student.day_set.all %}
                                        <div class="col-sm">
                                            {% for time in day.time_set.all %}
                                            {% if time.available %}
                                            <input type="checkbox" class="bg-light btn-check" name="available_times" id="{{ day.day }}{{ time.time }}" value="{{ day.day }}{{ time.time }}" autocomplete="off" checked>
                                            {% else %}
                                            <input type="checkbox" class="bg-light btn-check " name="available_times" id="{{ day.day }}{{ time.time }}" value="{{ day.day }}{{ time.time }}" autocomplete="off">
                                            {% endif %}
                                            <label class="btn border border-dark btn-outline-primary rounded-0" for="{{ day.day }}{{ time.time }}"><div style="height: 10px; width: 40"></div></label><br>
                                            {% endfor %}
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-primary" type="submit">Save Availability</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
    </script>
</body>


{% endblock %}




welcome/templates/welcome/newmeeting.html
{% load socialaccount %}
{% load bootstrap5 %}
{% load static %}
{% load custom_tags %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% include 'welcome/base.html' %}
{% block content %}
<body style="background-color:#f8f4fc;">
<br>
<h1 class="text-center">New Meeting:</h1><br>
<br>
<div class="container">
    <div class="row">
        <div class ="col-md-5 bg-light">
            <form action="{% url 'confmeeting' reciever.id %}" method = "post">
                {% csrf_token %}
                <br>
                <br><br>
                <div class="mb-3">
                    <label for="title" class="form-label">Title</label>
                    <input type="text" class="form-control" id="title" name="title" required>
                </div>
                <div class="mb-3">
                    <label for="date" class="form-label">Date</label>
                    <input type="date" class="form-control" id="date" name="date" required>
                </div>
                <div class="mb-3">
                    <label for="time" class="form-label">Time</label>
                    <input type="time" class="form-control" id="time" name="time" required>
                </div>
                <br>
                <p class="text-center">{{ errmsg }}</p>
                <div><div class="text-center"><button type="submit" value="submit" class="btn btn-primary">Confirm</button></div></div>
            </form>

        </div>
    
        <div class="bg-light col-md-5" style="height: 450px; width: 750">
            <br>
            <h3 class="text-center">{{ reciever.first_name }}'s Availablility:</h3>
            <div class="container">
                <div class="row gx-0 gy-0">
                    <div class="col-md-2" style="height: 345px; width: 75">
                        <div class="text-end" style="height: 20px; width: 0"></div>
                        <div class="text-end" style="height: 24px; width: 0">10:00AM</div>
                        <div class="text-end" style="height: 24px; width: 0">11:00AM</div>
                        <div class="text-end" style="height: 24px; width: 0">12:00PM</div>
                        <div class="pull-end" style="height: 24px; width: 0">1:00PM</div>
                        <div class="pull-right" style="height: 24px; width: 0">2:00PM</div>
                        <div class="text-center" style="height: 24px; width: 0"><p class="text-center">3:00PM</p></div>
                        <div class="text-end" style="height: 24px; width: 0">4:00PM</div>
                        <div class="text-end" style="height: 24px; width: 0">5:00PM</div>
                        <div class="text-end" style="height: 24px; width: 0">6:00PM</div>
                        <div class="text-end" style="height: 24px; width: 0">7:00PM</div>
                        <div class="text-end" style="height: 24px; width: 0">8:00PM</div>
                        <div class="text-end" style="height: 24px; width: 0">9:00PM</div>
                        <div class="text-end" style="height: 24px; width: 0">10:00PM</div>
                    </div>
                    <div class = "col-lg">
                        <div class ="row gx-0 gy-0">
                            <h5 class="col-sm">Mon</h5>
                            <h5 class="col-sm">Tues</h5>
                            <h5 class="col-sm">Wed</h5>
                            <h5 class="col-sm">Thur</h5>
                            <h5 class="col-sm">Fri</h5>
                            <h5 class="col-sm">Sat</h5>
                            <h5 class="col-sm">Sun</h5>
                        </div>
                        <div class="row gx-0 gy-0">
                            {% for day in reciever.day_set.all %}
                                <div class="col-sm">
                                    {% for time in day.time_set.all %}
                                        {% if time.available %}
                                            <div class="bg-primary border-primary" style="height: 24px; width: 75"></div>
                                        {% else %}
                                            <div class="border border-primary" style="height: 24px; width: 75"></div>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}

welcome/templates/welcome/other_profile.html
{% load socialaccount %}
{% load bootstrap5 %}
{% load static %}
{% load custom_tags %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% include 'welcome/base.html' %}
{% block content %}
<body style=" background-color:#159ec8c2;">
    <div class="d-flex justify-content-center" >
        <div class="bg-light d-flex justify-content-center" style="height: 950px; width: 850;">
            <div class="bg-light" style="height: 550px; width: 700;">
                <div class="border-bottom border-dark"><h1>{{ student.first_name }} {{student.last_name }}</h1></div>
                <br>
                
                <div class="text-center" style=" background-color:#ececec;" >
                    <h3>Bio:</h3>
                    {% if student.bio %}
                        <p class="h-50 overflow-auto text-wrap text-break p-2">{{ student.bio.content }}</p>
                    {% else %}
                        <p>Nothing here yet ¯\_(ツ)_/¯</p>
                    {% endif %}
                </div>
                <h3 class="text-center">Availablility:</h3>
                <div class="container text-center">
                    <div class="row gx-0 gy-0">
                        <div class="col-md-2" style="height: 345px; width: 75">
                            <div class="text-end" style="height: 20px;"></div>
                            <div class="text-end" style="height: 24px;">10:00AM</div>
                            <div class="text-end" style="height: 24px;">11:00AM</div>
                            <div class="text-end" style="height: 24px;">12:00PM</div>
                            <div class="text-end" style="height: 24px;">1:00PM</div>
                            <div class="text-end" style="height: 24px; ">2:00PM</div>
                            <div class="text-end" style="height: 24px;">3:00PM</div>
                            <div class="text-end" style="height: 24px; ">4:00PM</div>
                            <div class="text-end" style="height: 24px;">5:00PM</div>
                            <div class="text-end" style="height: 24px;">6:00PM</div>
                            <div class="text-end" style="height: 24px;">7:00PM</div>
                            <div class="text-end" style="height: 24px;">8:00PM</div>
                            <div class="text-end" style="height: 24px;">9:00PM</div>
                            <div class="text-end" style="height: 24px;">10:00PM</div>
                        </div>
                        <div class = "col-lg">
                            <div class ="row gx-0 gy-0">
                                <h5 class="col-sm">Mon.</h5>
                                <h5 class="col-sm">Tues.</h5>
                                <h5 class="col-sm">Wed.</h5>
                                <h5 class="col-sm">Thur.</h5>
                                <h5 class="col-sm">Fri.</h5>
                                <h5 class="col-sm">Sat.</h5>
                                <h5 class="col-sm">Sun.</h5>
                            </div>
                            <div class="row gx-0 gy-0">
                                {% for day in student.day_set.all %}
                                    <div class="col-sm">
                                        {% for time in day.time_set.all %}
                                            {% if time.available %}
                                                <div class="bg-primary border-primary" style="height: 24px; width: 75"></div>
                                            {% else %}
                                                <div class="border border-primary" style="height: 24px; width: 75"></div>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <br>
                {% if student in user.user.friends.all %}
                    <div class="clearfix">
                        <div class="float-start"><a href="{% url 'newmeeting' student.id %}" class="btn btn-primary">Schedule Meeting</a></div>
                    </div>
                {% else %}
                    {% if student in sent_requests %}
                        <div class="text-center"><button type="button" class="btn btn-secondary" disabled>Friend Request Pending</button></div>
                    {% else %}
                        <div class="text-center"><a href="{% url 'send friend request' student.id %}" class="btn btn-success" value="enter">Send Friend Request</a></div>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        
    </div>
    
</body>

{% endblock %}


welcome/templates/welcome/search.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>